source "https://rubygems.org"
gem "middleman"
gem "middleman-minify-html"
gem "middleman-imageoptim"
gem "middleman-deploy"
gem "middleman-cdn"
gem "middleman-favicon-maker"
gem "middleman-autoprefixer"
